name: ratemyresume
channels:
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.7.2
  - boto3=1.34.82
  - botocore=1.34.82
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.26.0
  - ca-certificates=2024.3.11
  - cairo=1.16.0
  - click=8.1.7
  - curl=8.5.0
  - django-storages=1.14.3
  - django=5.0.2
  - expat=2.5.0
  - fontconfig=2.13.94
  - freetype=2.10.4
  - gettext=0.21.1
  - glib=2.69.1
  - icu=73.2
  - jmespath=1.0.1
  - jpeg=9e
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libcurl=8.5.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libiconv=1.17
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - ncurses=6.4
  - openjpeg=2.4.0
  - openssl=3.2.0
  - pcre=8.45
  - pdf2image=1.17.0
  - pillow=10.2.0
  - pip=23.3.1
  - pixman=0.40.0
  - poppler-data=0.4.12
  - poppler=0.81.0
  - pysocks=1.7.1
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python=3.12.1
  - readline=8.2
  - s3transfer=0.10.1
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - sqlparse=0.4.4
  - tk=8.6.13
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=2.2.1
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - psycopg2>=2.9,<2.10 --no-binary psycopg2
