# Generated by Django 5.0.2 on 2024-02-25 20:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_alter_comment_id_alter_rating_id_alter_resume_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='commentsEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='isHidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='isPrivate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ratingsEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PrivateGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('allowJoinRequests', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_privateGroup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.privategroup')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateGroupBoardComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=2000)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.privategroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrivateGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.privategroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.AddField(
            model_name='privategroup',
            name='members',
            field=models.ManyToManyField(related_name='user_privateGroup', through='resumes.UserPrivateGroupMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
