# Generated by Django 5.0.2 on 2024-02-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_commentsenabled_resume_ishidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privategroup',
            name='name',
            field=models.CharField(default='fillername', max_length=200),
            preserve_default=False,
        ),
    ]
