# Generated by Django 5.0.2 on 2024-02-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_groupinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvite',
            name='text',
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='text',
        ),
    ]
