# Generated by Django 5.0.2 on 2024-02-27 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_remove_groupinvite_text_remove_joinrequest_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together={('invitee', 'group')},
        ),
    ]
