# Generated by Django 5.0.2 on 2024-02-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_alter_groupinvite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvite',
            name='action',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='action_at',
            field=models.DateTimeField(null=True),
        ),
    ]
