# Generated by Django 5.0.2 on 2024-02-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_groupinvite_action_groupinvite_action_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together=set(),
        ),
    ]
