# Generated by Django 5.0.2 on 2024-02-28 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0013_joinrequest_action_joinrequest_action_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='isHidden',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='isPrivate',
        ),
        migrations.AddField(
            model_name='resume',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('visible_to_my_groups', 'Visible To My Groups'), ('shared_with_specific_groups', 'Shared With Specific Groups'), ('hidden', 'Hidden')], default='hidden', max_length=27),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ResumeGroupViewingPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.privategroup')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
            ],
            options={
                'unique_together': {('resume', 'group')},
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='groupsSharedWith',
            field=models.ManyToManyField(through='resumes.ResumeGroupViewingPermissions', to='resumes.privategroup'),
        ),
    ]
