# Generated by Django 5.0.2 on 2024-02-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0014_remove_resume_ishidden_remove_resume_isprivate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('signed_in_users', 'Signed In Users'), ('visible_to_my_groups', 'Visible To My Groups'), ('shared_with_specific_groups', 'Shared With Specific Groups'), ('hidden', 'Hidden')], max_length=27),
        ),
    ]
