# Generated by Django 5.0.2 on 2024-03-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0016_alter_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
